CREATE DATABASE NovoDatabase

GO
CREATE TABLE PROJECT_COORDINATOR(
CoordinatorId INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
Initials NVARCHAR(4)
);

CREATE TABLE PROJECT(
ProjectId INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
ProjectName NVARCHAR(255),
Complexity NVARCHAR(50),
CoordinatorId INT FOREIGN KEY REFERENCES PROJECT_COORDINATOR(CoordinatorId)
);

CREATE TABLE PHASE(
PhaseId INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
Length INT,
Phase NVARCHAR(20),
ProjectId INT FOREIGN KEY REFERENCES PROJECT(ProjectId)
);

CREATE TABLE PROJECT_LENGTH(
ProjectLengthId INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
StartDate DATE,
EndDate DATE,
ProjectId INT FOREIGN KEY REFERENCES PROJECT (ProjectId)
);

CREATE TABLE PROJECT_ROLE_REQUIREMENT(
ProjectRoleRequirementId INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
JobRole NVARCHAR(50),
RequiredResources INT,
ProjectId INT FOREIGN KEY REFERENCES PROJECT(ProjectId)
);

CREATE TABLE RESOURCE(
ResourceId INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
Email NVARCHAR(20),
Initials NVARCHAR(4),
JobRole NVARCHAR(30),
Availability BIT,
ProjectId INT FOREIGN KEY REFERENCES PROJECT(ProjectId)
);
