@startuml
hide empty method
hide footbox /' Fjerner aktør og system i bunden'/


'Aktører'
Actor ": Projektkoordinator" as L
participant ":System" as S


'Commands'
L -> S: OpretProjekt(projektNavn, kompleksitet, antalTimer, startDato, slutDato, )
S --> L: System opretter projekt


S --> L: System opretter fase

L -> S: TilføjRessource(initialer, mail, rolle, ledighed)
S --> L: System tilføjer ressource

@enduml