@startuml
hide circle
hide empty members

skinparam padding 10
skinparam nodesep 100
skinparam ranksep 100

Projektmanager "1" ---right--- "1..*" Projekt
Fase "8" ---left--- "1" Projekt
Fase "1..*" ---right--- "1..*" Ressource

'Konceptuelle klasser
Class Projektmanager
{
    initialer
}

Class Ressource
{
    initialer
    rolle
    antalTimer
    ledighed
}

Class Fase
{
    faseNavn
    startDato
    slutDato
}

Class Projekt
{
    projektNavn
    kompleksitet
    startDato
    slutDato
}




@enduml